trunk/opentrials/repository/urls.py
from django.conf.urls.defaults import *
from django.views.generic.list_detail import object_detail, object_list

from repository.models import ClinicalTrial

from repository.views import edit_trial_index, full_view, index, step_1, step_2, step_3
from repository.views import step_4, step_5, step_6, step_7, step_8, step_9, new_institution
from repository.views import trial_registered, trial_view, recruiting, trial_ictrp, trial_otxml
from repository.views import all_trials_ictrp


urlpatterns = patterns('',
    url(r'^edit/(\d+)/$', edit_trial_index, name='repository.edittrial'),
    url(r'^view/(?P<trial_pk>\d+)/$', trial_view, name='repository.trialview'),
    url(r'^new_institution/$', new_institution, name='new_institution'),
    url(r'^step_1/(\d+)/$', step_1, name='step_1'),
    url(r'^step_2/(\d+)/$', step_2, name='step_2'),
    url(r'^step_3/(\d+)/$', step_3, name='step_3'),
    url(r'^step_4/(\d+)/$', step_4, name='step_4'),
    url(r'^step_5/(\d+)/$', step_5, name='step_5'),
    url(r'^step_6/(\d+)/$', step_6, name='step_6'),
    url(r'^step_7/(\d+)/$', step_7, name='step_7'),
    url(r'^step_8/(\d+)/$', step_8, name='step_8'),
    url(r'^step_9/(\d+)/$', step_9, name='step_9'),
    #public
    url(r'^recruiting/$', recruiting, name='repository.recruiting'),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/$', trial_registered, name='repository.trial_registered'),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/xml/ictrp/$', trial_ictrp, name='repository.trial_ictrp'),
    url(r'^all/xml/ictrp$', all_trials_ictrp),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/xml/ot/$', trial_otxml, name='repository.trial_otxml'),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/v(?P<trial_version>\d+)/$', trial_registered, name='repository.trial_registered_version'),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/v(?P<trial_version>\d+)/xml/ictrp/$', trial_ictrp, name='repository.trial_ictrp_version'),
    url(r'^(?P<trial_fossil_id>[0-9A-Za-z-]+)/v(?P<trial_version>\d+)/xml/opentrials/$', trial_otxml, name='repository.trial_otxml_version'),
    url(r'^$', index, name='repository.index'),
)

trunk/opentrials/urls.py
# -*- encoding: utf-8 -*-

# OpenTrials: a clinical trials registration system
#
# Copyright (C) 2010 BIREME/PAHO/WHO, ICICT/Fiocruz e
#                    Ministério da Saúde do Brasil
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 2.1 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from registration.forms import RegistrationFormUniqueEmail

import utilities

from django.contrib import admin # Django admin UI
admin.autodiscover()             # Django admin UI

urlpatterns = patterns('',
    # Repository application
    url(r'^rg/', include('opentrials.repository.urls')),

    # Tickets application
    url(r'^ticket/', include('opentrials.tickets.urls')),

    # Assistance application
    url(r'^assistance/', include('opentrials.assistance.urls')),

    # Review application
    url(r'^', include('opentrials.reviewapp.urls')),

    # Django admin UI and documentation
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^decs/', include('opentrials.decsclient.urls')),
    
    url(r'^icd10/', include('opentrials.icd10client.urls')),
    
    # setting django-registration to use unique email form
    url(r'^accounts/register/$', 'registration.views.register', 
        {'backend': 'registration.backends.default.DefaultBackend', 
        'form_class': RegistrationFormUniqueEmail},
        name='registration_register'),

    # django-registration views
    url(r'^accounts/', include('registration.urls')),

    # system diagnostic views (may be disabled in production)
    url(r'^diag/', include('opentrials.diagnostic.urls')),
    
    (r'^i18n/', include('django.conf.urls.i18n')),
)

from django.conf import settings
if settings.DEBUG:
    # serve static files from develpment server
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

    # Serve static XML files, specially DTD for XML references
    import os, repository
    REPOSITORY_XML_ROOT = os.path.join(os.path.dirname(repository.__file__), 'xml')
    urlpatterns += patterns('',
        url(r'^xml/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': REPOSITORY_XML_ROOT}),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

trunk/opentrials/reviewapp/models.py
from datetime import datetime

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes import generic
from django.utils import simplejson

from repository.models import ClinicalTrial, Institution
from repository.choices import PROCESSING_STATUS, PUBLISHED_STATUS, ARCHIVED_STATUS
from repository.serializers import deserialize_trial
from tickets.models import Ticket
from utilities import safe_truncate
from vocabulary.models import CountryCode
from polyglot.models import Translation, MANAGED_LANGUAGES_LOWER
from fossil.models import Fossil

from repository.trial_validation import TRIAL_FORMS
from consts import REMARK, MISSING, PARTIAL, COMPLETE
from django.conf import settings
from deleting.models import ControlledDeletion

SUBMISSION_STATUS = [
    ('draft', _('draft')), # clinical trial is 'processing'
    ('pending', _('pending')), # clinical trial remains 'processing'
    ('approved', _('approved')), # clinical trial is 'published'
    ('resubmit', _('resubmit')), # clinical trial remains 'processing'
]
STATUS_DRAFT = SUBMISSION_STATUS[0][0]
STATUS_PENDING = SUBMISSION_STATUS[1][0]
STATUS_APPROVED = SUBMISSION_STATUS[2][0]
STATUS_RESUBMIT = SUBMISSION_STATUS[3][0]

SUBMISSION_TRANSITIONS = {
    STATUS_DRAFT: [STATUS_PENDING],
    STATUS_PENDING: [STATUS_APPROVED, STATUS_RESUBMIT],
    STATUS_APPROVED: [],
    STATUS_RESUBMIT: [STATUS_DRAFT],
}

ACCESS = [
    ('public', _('Public')),
    ('private', _('Private')),
]

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    preferred_language = models.CharField(_('Preferred language'),max_length=10,
                                choices=settings.MANAGED_LANGUAGES_CHOICES,
                                default=settings.MANAGED_LANGUAGES_CHOICES[-1][0])
                                
    def amount_submissions(self):
        return u"%03d" % (Submission.objects.filter(creator=self.user).count())

    def amount_tickets(self):
        return u"%03d" % (Ticket.objects.filter(creator=self.user).count())

class Submission(ControlledDeletion):
    class Meta:
        ordering = ['-created']
        permissions = (
            ("review", "Can review"),
        )

    creator = models.ForeignKey(User, related_name='submission_creator', editable=False)
    created = models.DateTimeField(default=datetime.now, editable=False)
    updater = models.ForeignKey(User, null=True, related_name='submission_updater', editable=False)
    updated = models.DateTimeField(null=True, editable=False)
    title = models.TextField(u'Scientific title', max_length=2000)
    primary_sponsor = models.ForeignKey(Institution, null=True, blank=True,
                                    verbose_name=_('Primary Sponsor'))

    trial = models.OneToOneField(ClinicalTrial, null=True)
    status = models.CharField(_('Status'), max_length=64,
                              choices=SUBMISSION_STATUS,
                              default=SUBMISSION_STATUS[0][0])
    fields_status = models.TextField(_('Fields Status'), max_length=512, null=True, 
                                     blank=True, editable=False)
    language = models.CharField(_('Submission language'), max_length=10,
                                choices=settings.MANAGED_LANGUAGES_CHOICES,
                                default=settings.DEFAULT_SUBMISSION_LANGUAGE)
    staff_note = models.TextField(_('Submission note (staff use only)'), max_length=255,
                                    blank=True)

    def save(self, *args, **kwargs):
        if self.id:
            self.updated = datetime.now()
        if self.status == STATUS_APPROVED and self.trial.status == PROCESSING_STATUS:
            self.trial.status = PUBLISHED_STATUS
            self.trial.save()

        super(Submission, self).save(*args, **kwargs)

    def short_title(self):
        return safe_truncate(self.title, 120)

    def creator_username(self):
        return self.creator.username

    def __unicode__(self):
        return self.short_title()

    def get_mandatory_languages(self):
        langs = set([u'en'])
        if self.trial.primary_sponsor is not None:
            langs.add(self.trial.primary_sponsor.country.submission_language)

        for rc in self.trial.recruitment_country.all():
            langs.add(rc.submission_language)

        return langs.intersection(set(MANAGED_LANGUAGES_LOWER))

    def get_trans_languages(self):
        return self.get_mandatory_languages() - set([self.language])

    def get_secondary_language(self):
        sec = None
        for lang in self.get_mandatory_languages():
            # fixme: get from settings
            if lang != 'en':
                sec = lang.lower()
                break
        return sec

    def get_absolute_url(self):
        # TODO: use reverse to replace absolute path
        return '/accounts/submission/%s/' % self.id

    def init_fields_status(self):
        # sets the initial status of the fields
        fields_status = {}
        FIELDS = {
            TRIAL_FORMS[0]: MISSING, TRIAL_FORMS[1]: PARTIAL, TRIAL_FORMS[2]: MISSING,

            TRIAL_FORMS[3]: MISSING, TRIAL_FORMS[4]: MISSING, TRIAL_FORMS[5]: MISSING, 
            TRIAL_FORMS[6]: MISSING, TRIAL_FORMS[7]: MISSING, TRIAL_FORMS[8]: PARTIAL
        }
        for lang in self.get_mandatory_languages():
            lang = lang.lower()
            fields_status.update({lang: dict(FIELDS)})
            if lang == self.language.lower():
                fields_status[lang].update({TRIAL_FORMS[0]: PARTIAL})
        
        self.fields_status = simplejson.dumps(fields_status)
        self.save()

    def get_fields_status(self):
        if not getattr(self, '_fields_status', None):
            self._fields_status = simplejson.loads(self.fields_status)

        return self._fields_status

    def get_status(self):
        status = [field for step in self.get_fields_status().values() for field in step.values()]
        if REMARK in status:
            return REMARK
        elif MISSING in status:
            return MISSING
        elif PARTIAL in status:
            return PARTIAL
        return COMPLETE
        
    def can_delete(self):
        if Fossil.objects.filter(object_id=self.trial.pk).count() > 0:
            return False
        return self.status in [SUBMISSION_STATUS[0][0]]

class RecruitmentCountry(models.Model):
    class Meta:
        verbose_name_plural = _('Recruitment Countries')

    submission = models.ForeignKey(Submission)
    country = models.ForeignKey(CountryCode, verbose_name=_('Country'), related_name='submissionrecruitmentcountry_set')

class Attachment(models.Model):
    class Meta:
        verbose_name_plural = _('Attachments')
    file = models.FileField(_('File'), max_length=250, upload_to=settings.ATTACHMENTS_DIR, blank=True)
    attach_url = models.URLField(_('Link'), blank=True)
    description = models.TextField(_('Description'),blank=True,max_length=8000)
    submission = models.ForeignKey(Submission)
    public = models.BooleanField(_('Public'))

    def get_relative_url(self):
        return self.file.url.replace(settings.PROJECT_PATH, u'')
        
    def __unicode__(self):
        return u"%s" % self.description
        

REMARK_STATUS = [
    # initial state, as created by reviewer
    ('open', _('Open')),
    # marked as noted by user
    ('acknowledged', _('Acknowledged')),
    # final state, after reviewer verifies changes by the user
    ('closed', _('Closed')),
]

REMARK_TRANSITIONS = {
    'open':['acknowledged'],
    'acknowledged':['closed','open'],
    'closed':[],
}

class RemarksOpen(models.Manager):
    def get_query_set(self):
        return super(RemarksOpen, self).get_query_set().filter(status__exact='open')

class RemarksAcknowledged(models.Manager):
    def get_query_set(self):
        return super(RemarksAcknowledged, self).get_query_set().filter(status__exact='acknowledged')

class RemarksClosed(models.Manager):
    def get_query_set(self):
        return super(RemarksClosed, self).get_query_set().filter(status__exact='closed')

class Remark(models.Model):
    ''' A reviewer comment regarding a submission field.

    The remark is directed at the field identified by the context attribute.
    '''
    creator = models.ForeignKey(User, editable=False)
    created = models.DateTimeField(default=datetime.now, editable=False)
    submission = models.ForeignKey(Submission)
    context = models.CharField(_('Context'), max_length=256, blank=True)
    text = models.TextField(_('Text'), max_length=2048)
    status = models.CharField(_('Status'), max_length=16, choices=REMARK_STATUS,
                              default=REMARK_STATUS[0][0])

    objects = models.Manager()
    status_open = RemarksOpen()
    status_acknowledged = RemarksAcknowledged()
    status_closed = RemarksClosed()

    def __unicode__(self):
        return '%s:%s' % (self.pk, self.submission_id)

    def short_text(self):
        return safe_truncate(self.text, 60)
        
    def context_title(self):
        return _(self.context.title().replace('-', ' '))

NEWS_STATUS = [
    ('pending', _('Pending')),
    ('published', _('Published')),
]

class News(models.Model):

    class Meta:
        verbose_name_plural = _('News')

    title = models.CharField(_('Title'), max_length=256)
    text = models.TextField(_('Text'), max_length=2048)
    created = models.DateTimeField(default=datetime.now, editable=False)
    creator = models.ForeignKey(User, related_name='news_creator', editable=False)
    status = models.CharField(_('Status'), max_length=16, choices=NEWS_STATUS,

trunk/opentrials/repository/templates/repository/add_clinicalTrials.html
{% extends "base.html" %}
{% load i18n %}
{% block body_title %}{% trans "Add a new Clinical Trial Record" %}{% endblock %}

{% block body %}
    <form action="./" method="POST">{% csrf_token %}
        <table>
        {{form.as_table}}
        </table>
        <input type="submit">
    </form>
{% endblock %}

trunk/opentrials/repository/templates/repository/add_done.html
{% extends "base.html" %}

{% block body_title %}{% trans "Submission done" %}{% endblock %}

{% block body %}
    <h3>{{public_title}}, {% trans "added." %}</h3>
{% endblock %}

trunk/opentrials/repository/templates/repository/attachments.html
{% extends "repository/submission_step.html" %}
{% load i18n %}
{% load remark %}
{% load polyglot_tags %}

{% block body %}

    {% include "repository/messages.html" %}
    
    {% if remarks %}
    <div class="warning">
        <a class="minimize button" onclick="$(this.parentNode).toggleClass('warning-minimized').find('ul').toggle('slow')"><img src="{{MEDIA_URL}}media/img/admin/arrow-down.gif"/></a>
        <a class="maximize button" onclick="$(this.parentNode).toggleClass('warning-minimized').find('ul').toggle('slow')"><img src="{{MEDIA_URL}}media/img/admin/arrow-up.gif"/></a>
        <h2>{% trans 'Remarks' %}</h2>
        <ul>
            {% for remark in remarks %}
            <li id="remark_{{ remark.id }}">{{ remark.text }}
                <input onclick="ack_remark({{ remark.id }})" type="button" style="font-size: 80%;" value="{% trans "Mark as reviewed" %}" title="{% trans "Mark as reviewed" %}" />
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <div class="required_fields"><span>(*)</span> {% trans 'Required fields' %}</div>
    
    <h2>{% trans title %}</h2>
    
    {% if existing_attachments %}
        <h3>{% trans 'Existing attachments' %}</h3>

        {% for attachment in existing_attachments %}
            <ul>
                {% if attachment.file %}
                <li>{% trans 'File' %}:
                    <a href="http://{{host}}{{attachment.get_relative_url}}">
                        http://{{host}}{{attachment.get_relative_url}}
                    </a>
                </li>
                {% else %}
                <li>{% trans 'File' %}:
                    <a href="{{attachment.attach_url}}">
                        {{attachment.attach_url}}
                    </a>
                </li>
                {% endif %}
                <li>{% trans 'Description' %}: {{attachment.description}}</li>
                <li>
                    <form action="./" method='POST'>{% csrf_token %}
                        <input type="hidden" name='remove' value='{{attachment.id}}'/>
                        <input type="button" value='{%trans "Remove" %}' onclick="if(confirm('{%trans "Remove this attachment?" %}')) submit()" />
                    </form>
                </li>
            </ul> 

        {% endfor %}
    {% endif %}
    
    <h3>{% trans 'New attachment form' %}</h3>
    <form action="./" method="POST" enctype="multipart/form-data" >{% csrf_token %}

        {% for formset in formsets %}
            {{ formset.management_form }}
            <fieldset>
            <legend>{{ formset.form.title }}</legend>


            <div class="{{formset.management_form.prefix}}">
            {% for form in formset.forms %}
                <table class="dataTable {% cycle 'even' 'odd' %}" cellspacing="0">
                    {{ form.as_table }}
                </table>
            {% endfor %}
            </div>
            <div style="text-align: center">
              <input onclick="cloneMore('div.{{formset.management_form.prefix}} table:last','{{formset.management_form.prefix}}')" type="button" value="{% trans "Add more" %}" />
            </div>
            </fieldset>
        {% endfor %}
        <input type="submit" value="{% trans "Save" %}" {% if not request.can_change_trial %}disabled="disabled"{% endif %}/>
    </form>

{% endblock %}

{% block endjs %}{{ block.super }}

<script type="text/javascript" src="{{MEDIA_URL}}js/multilingual.js"></script>

<script type="text/javascript">
    {% polyglot_js_constants available_languages %}

    $(document).ready(function() {
        $("select[multiple]").asmSelect({
                addItemTarget: 'bottom',
                animate: true,
                highlight: true,
                sortable: false
        });
        $('.dataTable th img').cluetip({sticky: true, closePosition: 'title',local:true, cursor: 'pointer'});
    });
</script>

<script type="text/javascript">
    $(document).ready(function() {
       $('select[name*="attach_type"]').change(function() {
         name = $(this)[0].name;
         value = $(this)[0].value;
         order = parseInt(name.replace(/[^0-9]/g, ''))

         if(value == 'file'){
             //hide url, show file
             $('input[name*="url"]')[order].disabled = true
             $('input[name*="file"]')[order].disabled = false
         }
         else{
             //hide file, show url
             $('input[name*="url"]')[order].disabled = false
             $('input[name*="file"]')[order].disabled = true
         }         
       });
     });
</script>

<script type="text/javascript">
    $(document).ready(function() {
        // Confirm before user leave page and lose modified data without save them
        $('form.confirm-before-leave').submit(function(){
            $(this).data('modified', false);
            window.onbeforeunload = null;
        }).each(function(){
            // Sets this form to modified as false, but after some field be modified, so update this attribute to true
            $(this).data('modified', false);
        });
        
        // Sets inputs change event to set form modified as true
        $('form.confirm-before-leave').find(':input').change(function(){
            $(this).parents('form').data('modified', true);

            // When a user leaves the current page without save, and has modified some field, asks for its confirmation
            window.onbeforeunload = confirmExit;
            function confirmExit(){
                // TODO: translate
                return '{% trans 'You have done modifications on some fields. Are you sure you want to leave without save before?' %}';
            }
        });
    });
</script>
{% endblock %}

trunk/opentrials/repository/templates/repository/clinicaltrial_list.html
{% extends "base.html" %}

{% load i18n %}

{% block body_title %}{% trans "Clinical Trials" %}{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Registered Trials' %}</big>
{% endblock %}

{% block body %}

    {% if objects.object_list %}
        {% for ct in objects.object_list %}
        <table class="trial_table">
            <tr>
                <td class="trial_label" width="50%">{% trans 'Title' %}</td>
                <td class="trial_label" width="30%">{% trans 'Primary Id Number' %}</td>
                <td class="trial_content" width="20%"><a href="{% url repository.trial_registered ct.trial_id %}">{{ ct.trial_id }}</a></td>
            </tr>
            <tr>
                <td class="trial_title" rowspan="2"><a href="{% url repository.trial_registered ct.trial_id %}">{{ ct.main_title }}</a></td>
                <td class="trial_label">{% trans 'Recruitment Status' %}</td>
                <td class="trial_content">{{ ct.rec_status }}</td>
            </tr>
            <tr>
                <td class="trial_label">{% trans 'Date of Registration' %}</td>
                <td class="trial_content">{{ ct.date_registration }}</td>
            </tr>
        </table>
        {% endfor %}
        
        {% if paginator.num_pages > 1 %}
        <div class="pagination">
            {% if objects.has_previous %}
                <a href="?page=1"><<</a>
                <a href="?page={{ objects.previous_page_number }}"><</a>
            {% endif %}
            
            {% for p in paginator.page_range %}
                {% if p == page %}
                  <span class="current">
                      {{ p }}
                  </span>
                {% else %}
                    <a href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}
            
            {% if objects.has_next %}
                  <a href="?page={{ objects.next_page_number }}">></a>
                  <a href="?page={{ paginator.num_pages }}">>></a>
            {% endif %}
        </div>
        {% endif %}

    {% else %}
        {% if q %}
             <p>{% trans 'No clinical trial has been found with the term:' %} {{ q }}</p>
        {% else %}
            <p>{% trans 'No clinical trial has been registered.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

trunk/opentrials/repository/templates/repository/new_institution.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>{{ form.title }}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        
        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/style.css"/>
        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/jquery.cluetip.css"/>
        
        <style type="text/css">
            fieldset  {
                margin: 2em;
            }
            form table.dataTable th {
                width: 25%;
            }
        </style>
        
        <script type="text/javascript" src="{{ MEDIA_URL }}js/local/jquery.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/local/jquery-ui.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.cluetip.min.js" type="text/javascript"></script>
        
        <script type="text/javascript">
            // customization for the Brazilian registry of clinical trials
            // #190 Show Brazil at the beginning of the selects
            $(document).ready(function(){
                $("#id_country option").first().after($("#id_country option[value=1]"));
            });
        </script>
        
        <script type="text/javascript">
            function new_institution(){
                var target = document.location.toString();
                if(target.match('#')){
                    target = target.split('#')[1];
                }
                
                if(target==='new_contact'){
                    new_institution_contact(target);
                }else if(target==='primary_sponsor'){
                    new_institution_field(target);
                }else{
                    new_institution_sponsors(target);
                }
            }

            function new_institution_field(target){
                var data = '', op = '';
                $('form *[name]').each(function(){data+=op+this.name+'='+this.value;op='&';});
                $.post(
                    $('form').attr('action'),
                    data,
                    function(data, ts, xmlhttp){
                        if(data.match(/<[a-z]+[^>]+>/)){
                            $("table.dataTable").html(data);
                        }else {
                            data=$.parseJSON(data);
                            var select = opener.$('tr.'+target+' select');
                            var newoption = opener.$('<option>').attr('value',data[0].pk).html(data[0].fields.name);
                            select.append(newoption).val(data[0].pk);
                            window.close();
                        }
                    },
                    'text'
                );
            }

            function new_institution_sponsors(target){
                var data = '', op = '';
                $('form *[name]').each(function(){data+=op+this.name+'='+this.value;op='&';});
                $.post(
                    $('form').attr('action'),
                    data,
                    function(data, ts, xmlhttp){
                        if(data.match(/<[a-z]+[^>]+>/)){
                            $("table.dataTable").html(data);
                        }else {
                            data=$.parseJSON(data);
                            opener.$('select').each(function(){
                                var newoption = opener.$('<option>').attr('value',data[0].pk).html(data[0].fields.name);
                                opener.$(this).append(newoption);
                            });
                            var total = opener.$("div."+target+" select").length;
                            var targetSel = opener.$('#id_'+target+'-'+(total-1)+'-institution')[0];
                            if(targetSel.selectedIndex === 0){
                                targetSel.selectedIndex = $(targetSel).find("option").length-1;
                            }else{
                                opener.cloneMore('div.'+target+' table:last',target);
                                targetSel = opener.$('#id_'+target+'-'+total+'-institution')[0];
                                targetSel.selectedIndex = $(targetSel).find("option").length-1;
                            }
                            window.close();
                        }
                    },
                    'text'
                );
            }
            
            function new_institution_contact(target){
                var data = '', op = '';
                $('form *[name]').each(function(){data+=op+this.name+'='+this.value;op='&';});
                $.post(
                    $('form').attr('action'),
                    data,
                    function(data, ts, xmlhttp){
                        if(data.match(/<[a-z]+[^>]+>/)){
                            $("table.dataTable").html(data);
                        } else {
                            data=$.parseJSON(data);
                            opener.$('select[id$=affiliation]').each(function(){
                                var newoption = opener.$('<option>').attr('value',data[0].pk).html(data[0].fields.name);
                                opener.$(this).append(newoption);
                            });
                            var total = opener.$("div."+target+" select[id$=affiliation]").length;
                            var targetSel = opener.$('#id_'+target+'-'+(total-1)+'-affiliation')[0];
                            if(targetSel.selectedIndex === 0){
                                targetSel.selectedIndex = $(targetSel).find("option").length-1;
                            }else{
                                opener.cloneMore('div.'+target+' table:last',target);
                                targetSel = opener.$('#id_'+target+'-'+total+'-affiliation')[0];
                                targetSel.selectedIndex = $(targetSel).find("option").length-1;
                            }
                            window.close();
                        }
                    },
                    'text'
                );
            }

            $(document).ready(function() {
                $('.dataTable th img').cluetip({sticky: true, closePosition: 'title',local:true, cursor: 'pointer'});
            });
        </script>
{% load i18n %}
    </head>
    <body>
        <form action="{% url new_institution %}" method="post" onsubmit="return false;">{% csrf_token %}
            <fieldset>
                <legend>{{ form.title }}</legend>
                <table class="dataTable" cellspacing="0">
                    {{ form.as_table }}
                </table>
                <input type="button" value="{% trans 'Save' %}" onclick="new_institution();"/>
            </fieldset>
        </form>
    </body>
</html>

trunk/opentrials/repository/templates/repository/step_2.html
{% extends "repository/trial_form.html" %}
{% load i18n %}
{% load polyglot_tags %}

{% block extra_buttons %}<input onclick="new_institution('{{formset.management_form.prefix}}')" type="button" value="{% trans 'New Institution' %}"/>{% endblock %}

{% block endjs %}{{ block.super }}
    <script type="text/javascript">
        function new_institution(target){
            return window.open('{% url new_institution %}#'+target,'n_i','status=0,location=0,height=380');
        }
    </script>
{% endblock %}
